services:
  web:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass

  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "8080:80"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    depends_on:
      - web
